[package]
name = "rte-sys"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
cfg-if = "1"

[build-dependencies]
anyhow = "1"
bindgen = { version = "0.73" }
cargo-emit = "0.2"
cc = "1"
log = { workspace = true }
pkg-config = "0.3"
pretty_env_logger = { workspace = true }

[features]
# bindgen = ["dep:bindgen"]
