[package]
name = "rte-sys"
version = "0.2.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "FFI bindings to DPDK"
links = "dpdk"
build = "build.rs"

[lib]
name = "rte_sys"
doctest = false

[features]
default = ["sse42"]
gen = ["bindgen"]
sse42 = []
avx = ["sse42"]
debug = []

[dependencies]
log = "0.3"
libc = "0.2"

[dev-dependencies]


[build-dependencies]
log = "0.3"
env_logger = "0.3"
gcc = "0.3"
bindgen = { git="https://github.com/flier/rust-bindgen.git", rev="0494698", optional=true }
