[package]
name = "rte-sys"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "FFI bindings to DPDK"
links = "dpdk"
build = "build.rs"

[dependencies]
libc = "0.2"
log = "0.3"

[dev-dependencies]
