[package]
name = "rte"
version.workspace = true
edition.workspace = true
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "Rust bindings to DPDK 20.11"
build = "build.rs"

[features]
default = []

[dependencies]
anyhow = "1"
log = { workspace = true }
bitflags = "2"
lazy_static = { workspace = true }
libc = "0.2"
time = "0.3"
cfile = "0.5"
rand = "0.10"
errno = "0.3"
num-traits = "0.2"
num-derive = "0.5"
itertools = { workspace = true }
thiserror = "2"

rte-sys = { path = "../rte-sys" }

[build-dependencies]
log = { workspace = true }
pretty_env_logger = { workspace = true }

[dev-dependencies]
pretty_env_logger = { workspace = true }
num_cpus = { workspace = true }
getopts = "0.2"
nix = "0.31"

[lib]
name = "rte"

[[example]]
name = "helloworld"
path = "examples/helloworld/main.rs"

# [[example]]
# name = "l2fwd"
# path = "examples/l2fwd/main.rs"

# [[example]]
# name = "kni"
# path = "examples/kni/main.rs"

[[example]]
name = "bond"
path = "examples/bond/main.rs"

[[example]]
name = "cmdline"
path = "examples/cmdline/main.rs"

[[example]]
name = "ethtool"
path = "examples/ethtool/main.rs"
