[package]
name = "rte-build"
version = "18.11.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "FFI bindings to DPDK"

[dependencies]
log = "0.4"
lazy_static = "1.2"
raw-cpuid = "6.1"
itertools = "0.7"
num_cpus = "1.0"
cc = "1.0"