// pub mod bitmap;
// mod config;
pub mod eal;
// pub mod keepalive;
pub mod launch;
pub mod lcore;
// pub mod log;
// mod rand;
pub mod dev;
pub mod malloc;
mod version;
// pub mod devargs;
// pub mod debug;
// pub mod spinlock;
pub mod byteorder;
// mod cycles;
pub mod memory;
// pub mod memzone;

// pub use self::config::{config};
// pub use self::cycles::*;
// pub use self::lcore::{socket_count, socket_id};
// pub use self::rand::{rand, srand};
pub use self::version::version;
